### ISSUE TITLE
may be anchor number is wrong

### ISSUE THREAD

**Issue by zhuangjunfei** [HelloRicky123/Siamese-RPN#11]
total anchor number is 289 not 255, that may influence the result

**Comment by shallowtoil** [comment]
Also, since in RPN you use instance size 271 to load pre-curated images with 255 size and enlarge the max_translate realm from 3 to 12, so in the random_crop step to augment training x images, the border of the images will be filled with 0. Yet I'm not sure how this would affect the ultimate results.

**Comment by HelloRicky123** [comment]
It is relevant to the score size.
