### ISSUE TITLE
train process

### ISSUE THREAD

**Issue by ucasqcz** [HelloRicky123/Siamese-RPN#15]
The ./siamrpn_30.pth is got after 20 epochs' 8e-4 lr and 30 epochs' 1e-2
what did this mean?
did you first train the model with 20 epochs' 8e-4 lr and 30 epochs' 1e-2, and then use the train.py script to train it again? 
if we want to train it from scratch, how to set the lr schedule?
thanks

**Comment by HelloRicky123** [comment]
There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.

**Comment by ucasqcz** [comment]
> There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.

can you provide some main tricks during your tuning? by the way, youtube-bb only bring 1 auc gain?

**Comment by ucasqcz** [comment]
> There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.
i have tried the 59version without youtub-bb and change pairs_per_video_per_epoch = 10, during 50 epoch training, the auc on otb100 is only about 0.5, so how to modify the config file when we train the model with only VID dataset?

**Comment by HelloRicky123** [comment]
I can only get 0.51auc on otb100 without YouTube dataset。------------------ Original ------------------From: ucasqcz  <notifications@github.com>Date: Tue,Apr 2,2019 2:26 PMTo: HelloRicky123/Siamese-RPN <Siamese-RPN@noreply.github.com>Cc: HelloRicky123 <qftju12345@163.com>, Comment <comment@noreply.github.com>Subject: Re: [HelloRicky123/Siamese-RPN] train process (#15)
There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.
i have tried the 59version without youtub-bb and change pairs_per_video_per_epoch = 10, during 50 epoch training, the auc on otb100 is only about 0.5, so how to modify the config file when we train the model with only VID dataset?


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HelloRicky123/Siamese-RPN","title":"HelloRicky123/Siamese-RPN","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/HelloRicky123/Siamese-RPN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ucasqcz in #15: \u003e There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.\r\ni have tried the 59version without youtub-bb and change pairs_per_video_per_epoch = 10, during 50 epoch training, the auc on otb100 is only about 0.5, so how to modify the config file when we train the model with only VID dataset?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930",
"url": "https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ucasqcz** [comment]
> 0.51auc on otb100 without YouTube dataset

but i see your 54version can get 0.54 on otb50 without youtube-bb, but with same model which gets 0.5 on otb100, the performance on otb50 is only about 0.45, is this result correct?  generally, AUC result on otb50 is lower than otb100, so what is the correct config on OTB50 ?

**Comment by HelloRicky123** [comment]
There are otb50，otb100 and cvpr2013 totally 3 set of dataset.------------------ Original ------------------From: ucasqcz  <notifications@github.com>Date: Tue,Apr 2,2019 3:35 PMTo: HelloRicky123/Siamese-RPN <Siamese-RPN@noreply.github.com>Cc: HelloRicky123 <qftju12345@163.com>, Comment <comment@noreply.github.com>Subject: Re: [HelloRicky123/Siamese-RPN] train process (#15)
0.51auc on otb100 without YouTube dataset

but i see your 54version can get 0.54 on otb50 without youtube-bb, but with same model which gets 0.5 on otb100, the performance on otb50 is only about 0.45, is this result correct?  generally, AUC result on otb50 is lower than otb100, so what is the correct config on OTB50 ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HelloRicky123/Siamese-RPN","title":"HelloRicky123/Siamese-RPN","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/HelloRicky123/Siamese-RPN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ucasqcz in #15: \u003e 0.51auc on otb100 without YouTube dataset\r\n\r\nbut i see your 54version can get 0.54 on otb50 without youtube-bb, but with same model which gets 0.5 on otb100, the performance on otb50 is only about 0.45, is this result correct?  generally, AUC result on otb50 is lower than otb100, so what is the correct config on OTB50 ?"}],"action":{"name":"View Issue","url":"https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478880241"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478880241",
"url": "https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478880241",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ucasqcz** [comment]
> I can only get 0.51auc on otb100 without YouTube dataset。------------------ Original ------------------From: ucasqcz <notifications@github.com>Date: Tue,Apr 2,2019 2:26 PMTo: HelloRicky123/Siamese-RPN <Siamese-RPN@noreply.github.com>Cc: HelloRicky123 <qftju12345@163.com>, Comment <comment@noreply.github.com>Subject: Re: [HelloRicky123/Siamese-RPN] train process (#15) There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up. i have tried the 59version without youtub-bb and change pairs_per_video_per_epoch = 10, during 50 epoch training, the auc on otb100 is only about 0.5, so how to modify the config file when we train the model with only VID dataset? —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HelloRicky123/Siamese-RPN","title":"HelloRicky123/Siamese-RPN","subtitle":"GitHub repository","main_image_url":"[https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/HelloRicky123/Siamese-RPN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ucasqcz](https://github.com/HelloRicky123/Siamese-RPN%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@ucasqcz) in #15: \u003e There is a new version now in 59version folder. You can train with a pretrained model on imagenet with it without warm up.\r\ni have tried the 59version without youtub-bb and change pairs_per_video_per_epoch = 10, during 50 epoch training, the auc on otb100 is only about 0.5, so how to modify the config file when we train the model with only VID dataset?\r\n"}],"action":{"name":"View Issue","url":"[#15 (comment)](https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#15 (comment)](https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930)", "url": "[#15 (comment)](https://github.com/HelloRicky123/Siamese-RPN/issues/15#issuecomment-478861930)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
yes, but the 54version of your code also train the model without youtube, and the auc 
![image](https://user-images.githubusercontent.com/8789264/55387819-bac3de80-5564-11e9-9445-6ef0f6b4cab5.png) on OTB50 is nearly 10 points higher on the 59version, I am confused about your results, which is the test dataset for the 0.54 auc performance?

**Comment by longqiwf** [comment]
@HelloRicky123 @ucasqcz I used the siamrpn_30.pth which is your trained model to run test_OTB.py in 54vision and got the 0.45 auc on otb2015, what's wrong?

**Comment by HelloRicky123** [comment]
I format this repo and you can try it.
