### ISSUE TITLE
train the 54vision without yt_bb

### ISSUE THREAD

**Issue by ghost** [HelloRicky123/Siamese-RPN#30]
Hi, I trained your 54vision with VID and got Nan loss, then I reduce the LR it can run properly. I run the test_OTB.py with my trained model but error occured to data overflow, why？Awaiting your reply.

**Comment by HelloRicky123** [comment]
Maybe the predicted box has w or h under 0, or has cx,cy out of image.

**Comment by ghost** [comment]
Thanks for your reply, I noticed your 54vision because it need't to train on yt_bb, which takes a lot of time, when I run your train codes without any change, loss increasing until Nan occurs. I wonder why this happens, is your codes' problem?

**Comment by HelloRicky123** [comment]
I forget whether it use grad clip, if not, it should be tried several times to train.------------------ Original ------------------From: NatureRiver  <notifications@github.com>Date: Fri,Apr 26,2019 4:34 PMTo: HelloRicky123/Siamese-RPN <Siamese-RPN@noreply.github.com>Cc: HelloRicky123 <qftju12345@163.com>, Comment <comment@noreply.github.com>Subject: Re: [HelloRicky123/Siamese-RPN] train the 54vision without yt_bb(#30)Thanks for your reply, I noticed your 54vision because it need't to train on yt_bb, which takes a lot of time, when I run your train codes without any change, loss increasing until Nan occurs. I wonder why this happens, is your codes' problem?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HelloRicky123/Siamese-RPN","title":"HelloRicky123/Siamese-RPN","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/HelloRicky123/Siamese-RPN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@longqiwf in #30: Thanks for your reply, I noticed your 54vision because it need't to train on yt_bb, which takes a lot of time, when I run your train codes without any change, loss increasing until Nan occurs. I wonder why this happens, is your codes' problem?"}],"action":{"name":"View Issue","url":"https://github.com/HelloRicky123/Siamese-RPN/issues/30#issuecomment-486975831"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/HelloRicky123/Siamese-RPN/issues/30#issuecomment-486975831",
"url": "https://github.com/HelloRicky123/Siamese-RPN/issues/30#issuecomment-486975831",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
